---
title: "Title of dissertation here"
subtitle: 'Firstname Surname'
author: 
- 'Submitted in partial fulfillment of the requirements of the Degree of Doctor of Philosophy'
date: 'Date here'
header-includes: 
- \usepackage{placeins}
- \usepackage{booktabs}
- \usepackage{setspace}
- \usepackage{fancyhdr}
- \onehalfspacing
- \usepackage{caption}
- \usepackage{float}
- \usepackage{multirow}
- \captionsetup{justification=raggedright,singlelinecheck=false}
- \usepackage{geometry}
documentclass: book
classoption: oneside
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
linkcolor: black
fontsize: 12pt
linestretch: 1.5
bibliography: library.bib
csl: apa-mcmahon.csl
urlcolor: black
geometry: "a4paper, left=4cm, right=2.5cm, top=2.5cm, bottom=2.5cm"
graphics: yes
---

```{r setup, include=FALSE, fig.lp="fig:"}
knitr::opts_chunk$set(echo = TRUE, fig.width=5, fig.height=3, fig.pos='H')
library(ggplot2)
library(knitr)
```

\newpage
\FloatBarrier
```{r child='Originality.Rmd'}
```

\newpage
\FloatBarrier
```{r child='Abstract.Rmd'}
```

\setcounter{tocdepth}{2}
\tableofcontents
\listoftables
\listoffigures

\newpage
\FloatBarrier
```{r child='Abbreviations.Rmd'}
```

\newpage
\FloatBarrier
```{r child='Acknowledgements.Rmd'}
```

\newpage
\FloatBarrier
```{r child='Chapter1.Rmd'}
```

\newpage
\FloatBarrier
```{r child='Discussion.Rmd'}
```

\phantomsection
\pagestyle{plain}
\chapter*{References}
\addcontentsline{toc}{chapter}{References}
<div id="refs"></div>

\newpage
\FloatBarrier
```{r child='AppendixA.Rmd'}
```

